appId: host.exp.exponent
---
- tapOn: Skip
- waitForAnimationToEnd
- tapOn: 
    id: "menu-button"
- tapOn: Direction
- tapOn: 
    id: "inputStartLoc"
- inputText: 
    text: "ha"
    label: "Input start location no route error"
- tapOn: "Hall Building"
- tapOn:
    id: "inputDestLoc"
- inputText: 
    text: "gr"
    label: "Input destination location no route error"
- tapOn: "Grey Nuns Building"